# Generated by Django 4.0.4 on 2022-09-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_mainpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpost',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
